apiVersion: v1
kind: Service
metadata:
  name: testflight-svc
  namespace: skkim-01
spec:
  selector:
    app.kubernetes.io/name: testflight
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31100